# Generated by Django 2.1.2 on 2018-10-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userid',
            field=models.IntegerField(default=12),
        ),
    ]
